#!/bin/sh
# shell script to fix mis-ordered FLIBS on linux
inp=$1
l1=''
l2=''

## echo '### INP ' $inp
for d in $inp; do
###   echo '>>> ' $d
#         echo $l2 | grep -q "\\$d" >&/dev/null
#	 if [ $? -ne 0 ]; then  l2="$l2 $d" ; fi
#         echo ' -L  ' $l2
  case "$d" in
    -l*.o) 
         ;;
    -l*)  
         l1="$l1 $d" 
         ;;
    -L*)  
         l2="$l2 $d"  
         ;;
  esac
done

echo $l2 $l1
