bin_dir="/usr/local/bin"
lib_iff="-L/usr/local/lib -lifeffit "
lib_plt="-L/usr/local/pgplot -lpgplot -lpng -lz -L/usr/X11R6/lib -lX11"
lib_f77="-L/usr/lib/gcc-lib/i386-redhat-linux/3.2.2 -L/usr/lib/gcc-lib/i386-redhat-linux/3.2.2/../../.. -lfrtbegin -lg2c -lm -lgcc_s "
inc_iff="-I../../src/lib -I/usr/local/share/ifeffit/config"
