 Feff 6L.02
 iron in copper
 Calculating potentials and phases...
     free atom potential and density for atom type    0
     free atom potential and density for atom type    1
     overlapped potential and density for unique potential    0
     overlapped potential and density for unique potential    1
     muffin tin radii and interstitial parameters
     phase shifts for unique potential    0
     phase shifts for unique potential    1
 Feff done.  Have a nice day.
