 Feff 6L.02
 iron in copper
 Calculating potentials and phases...
     free atom potential and density for atom type    0
     free atom potential and density for atom type    1
     overlapped potential and density for unique potential    0
     overlapped potential and density for unique potential    1
     muffin tin radii and interstitial parameters
     phase shifts for unique potential    0
   Hard tests failed in fovrg.
  Muffin-tin radius may be too large; coordination number too small.
     phase shifts for unique potential    1
   Hard tests failed in fovrg.
  Muffin-tin radius may be too large; coordination number too small.
 Preparing plane wave scattering amplitudes...
   nncrit in prcrit       9
 Searching for paths...
     Rmax  5.7000  keep and heap limits   0.0000000   0.0000000
    Preparing neighbor table
     nfound  nheap  nheapx  nsc    r
       1000    234     278   4    5.2920
     Paths found     1758   (nheapx, nbx     278   4)
 Eliminating path degeneracies...
     Plane wave chi amplitude filter   2.50%
     Unique paths     21,  total paths     798
 Feff done.  Have a nice day.
